### ISSUE TITLE
Option "Add native lazy loading to images" leads to html-invalid syntax and on-page code print

### ISSUE THREAD

**Issue by imsadhappy** [arnowelzel/lightbox-photoswipe#17] opened 2020-04-09 12:49 UTC
Hi.

The issue appeared after update to 2.75. The issue has 2 parts below: A) results in invalid html syntax and a more severe one B) that results in on-page print of code. Basically, I've found A) because of B).

A) is the fact that `loading="lazy"` gets added in a wrong place that results in invalid html syntax.

`loading="lazy"` gets added after the / in img tag close, that basically turns `<img />` into `<img / loading="lazy">` whereas correct syntax would be `<img loading="lazy" />`. My best guess is that you'll need to rewrite your regex to foresee that img tag can be written like `<img>` or `<img />` with backslash. This issue is common for all images, unlike the next one.

B) The second issue below only happens inside WP 'blocks' (woocommerce product guttenberg block to be specific) and results in the following output: 
`<a href="..." class="wc-block-grid__product-link"><div class="wc-block-grid__product-image">><img width="678" height="678" ...`

If you look closer it adds `>` before `<img ...` Unlike A) which is not visible on page, this prints on page as text, so that `>` appears before image. Basically, I've found A) because of B) - I've noticed that after last update extra `>` symbols appeared on page.

This is also, as A) happens in the same place, because of incorrect preg_replace split of output string, and only if "Add native lazy loading to images" option is enabled. If option "Add native lazy loading to images" is disabled, neither A) or B) happen.

I've located the issue in lightbox-photoswipe.php (Version: 2.75, below lines refferenced for this version)

First here (from line : 599)

```
    function filterOutput($content)
    {
	    if ('1' === $this->add_lazyloading) {
		    $content = preg_replace_callback(
			    '/(<a.[^>]*href=["\'])(.[^"^\']*?)(["\'])([^>]*)(>)(((?!<\/a>).)*)(<img [^>]+)(>)(.*)(<\/a>)/sU',
			    array( $this, 'outputCallbackProperties' ),
			    $content
		    );
	    }
```

Preg-replace obviously breaks the output in a wrong way. Then here (from line: 566)

```
        // Add "lazy loading" to the image if needed
	    if ('1' === $this->add_lazyloading) {
		    if (strpos( $matches[8], 'loading="lazy"' ) === false) {
			    $matches[8] .= ' loading="lazy"';
		    }

		    return $matches[1] . $matches[2] . $matches[3] . $matches[4] . $attr . $matches[5] .
		           $matches[6] . $matches[7] . $matches[8] . $matches[9] . $matches[10] . $matches[11];
	    }
```

**Comment by arnowelzel** [comment] 2020-04-09 13:52
Unfortunately I can't reproduce this on my test site:

https://wordpress-demo.arnowelzel.de/lightbox-with-photoswipe/

**Comment by arnowelzel** [comment] 2020-04-09 14:19
Ok, I found a test case which shows the problem here as well. I'll see what I can do about this.

**Comment by arnowelzel** [comment] 2020-04-09 15:33
Fixed with https://github.com/arnowelzel/lightbox-photoswipe/commit/a7a5a15560940f348d569cf208c017afc5517ced

**Closed by arnowelzel** 2020-04-09 15:33 UTC
